apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregator
data:
  application.properties: |-
    spring.datasource.url=jdbc:mysql://mysql-read:3307/recommendation
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    spring.datasource.hikari.maximum-pool-size=5
  
    spring.jpa.show-sql=true
    spring.jpa.hibernate.ddl-auto=none
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
    spring.jpa.properties.hibernate.format_sql=true
  
    spring.liquibase.enabled=true
  
    kafka.bootstrapAddress=kafka:9092
  
    kafka.topic.currency.name=currency
    kafka.topic.currency-dlt.name=currency-dlq
    kafka.topic.currency-dlt.partitions=3
    kafka.topic.currency-dlt.replicas=1
  
    kafka.consumer.currency.offset=latest
    kafka.consumer.currency.count=3
    kafka.consumer.currency.max-poll-records=10
    kafka.consumer.currency.retry.interval=3
    kafka.consumer.currency.retry.attempts=4
    kafka.consumer.currency.aggregator.group.id=aggregator-group