apiVersion: v1
kind: ConfigMap
metadata:
  name: currency
data:
  application.properties: |-
    server.port=8081
    
    spring.datasource.url=jdbc:mysql://mysql-write:3308/recommendation
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    spring.datasource.hikari.maximum-pool-size=5

    spring.jpa.show-sql=true
    spring.jpa.hibernate.ddl-auto=none
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
    spring.jpa.properties.hibernate.format_sql=true

    spring.liquibase.enabled=true

    kafka.bootstrapAddress=kafka:9092

    kafka.topic.currency.name=currency
    kafka.topic.currency.partitions=3
    kafka.topic.currency.replicas=1

    crypto.recommendation.app.currency.load-data-on-startup=true
    crypto.recommendation.app.currency.data.csv=data/BTC_values.csv,data/DOGE_values.csv,data/ETH_values.csv,data/LTC_values.csv,data/XRP_values.csv